### POST to log a telemetry event
POST http://localhost/analytics/ HTTP/1.1
content-type: application/json

{
    "url": "demo URL",
    "ref": "demo referrer"
}

### Query: Latest
POST http://localhost/analytics/query/latest/ HTTP/1.1
content-type: application/json

{
    "count": "30"
}

### Query: Hourly
POST http://localhost/analytics/query/hourly/ HTTP/1.1
content-type: application/json

{
    "days": 30
}

### Query: Daily
POST http://localhost/analytics/query/daily/ HTTP/1.1
content-type: application/json

{
    "days": 30
}